### ISSUE TITLE
VnV plan initial version

### ISSUE THREAD

**Issue by Maryamvalian** [Maryamvalian/project741#10]
@smiths please check my VnV [plan](https://github.com/Maryamvalian/project741/blob/98f93a3c1a68d0c37de0369b22e5770353f3a7aa/docs/VnVPlan/VnVPlan.pdf)

**Comment by smiths** [comment]
Feedback on the VnV plan is attached.

[VnVPlan_Fdbck.pdf](https://github.com/Maryamvalian/project741/files/10863295/VnVPlan_Fdbck.pdf)
