### ISSUE TITLE
VnV: minor issues

### ISSUE THREAD

**Issue by joedf** [Maryamvalian/project741#12]
- [x] Revision history date format broken "14-0202023" and "16-0202023"
- [x] Section 4.4: my name! 😉 is "Joachim de <strike>Frostier</strike> Fourestier"
- [x] "FR" is listed in the table but not used. Maybe change it to just "R" like you have in 5.1 (test for functional requirements), or change the "R"s to "FR"s ?
- [x] Remove 7.2 Usability Survey Questions, since it's not needed/used?
- [x] in 3.2: "[...] but also <strike>W</strike>we will test [...]" - lowercase
- [x] in 4: two broken references? "Section ??"

**Comment by Maryamvalian** [comment]
All done! Thank you.
