### ISSUE TITLE
VnV: NFRs consistency? 

### ISSUE THREAD

**Issue by joedf** [Maryamvalian/project741#13]
In the VnV plan section 3.2 (objectives), the most important quality / NFR is said to be "Correctness".

Your SRS lists the following nonfunctional requirements: Accuracy, Usability, Maintainability and Portability.

However in the VnV plan - section 5.2, the only NFR tested is Reliability?

Should correctness be listed in 5.2 or at least in the SRS? Or reliability?

**Comment by Maryamvalian** [comment]
Updated section 3.2. For NFR, Reliability and portability will be tested. we will not test maintainability since we analyzed likely changes. Thanks!
