### ISSUE TITLE
VnV plan: list some used symbols

### ISSUE THREAD

**Issue by joedf** [Maryamvalian/project741#15]
This maybe a minor thing or not needed... no sure...
Anyway, I know that "F", "J", "M" and "S" are all well and nicely defined in the SRS.

However, maybe it would be good or nice to have... listing them in the VnV plan's Symbols table with a short description?

**Comment by Maryamvalian** [comment]
I personally think it is unnecessary, but respecting you, added the table to Appendix. Thank you both :)
