### ISSUE TITLE
VnV Plan 4.7: Pseudo-oracle credibility

### ISSUE THREAD

**Issue by LesleyWheat** [Maryamvalian/project741#16]
This is a not so relevant point to the assignment but why should you trust the website you're using as your pseudo-oracle? It looks like the program is a teaching example rather than meant to be production code.

**Comment by Maryamvalian** [comment]
Good point Lesley! But there are other ways of testing the correctness of the algorithm. For example the summation of internal results for the last joint and zero members.  By testing these situations we can even test the results of an unknown website to see if the provided solution is correct.
