### ISSUE TITLE
VnV Plan 4.7: Distance Formula

### ISSUE THREAD

**Issue by LesleyWheat** [Maryamvalian/project741#17]
Kind of a nitpicky point. As you said this is only 2D, you should specify $n$ is the dimensions or just replace it with a 2.

**Comment by Maryamvalian** [comment]
Since you did not mention the section, I'm not sure if we are on the same page. But n is the number of joints. For example for a triangle truss n=3. Please feel free to open a new issue, if I misunderstood your point
