### ISSUE TITLE
VnV Plan 5.1.2: Test 1 formula formatting

### ISSUE THREAD

**Issue by LesleyWheat** [Maryamvalian/project741#21]
![image](https://user-images.githubusercontent.com/29044132/220660700-521a2e87-15a7-4fe3-95c0-b6ae35fd7bcc.png)

Here latex is treating I and F as two different variables instead of one (it's showing I times F) as $I F$. Use mbox to remove the space so it shows as $\mbox{IF}$ (which is \mbox{IF} ).

**Comment by Maryamvalian** [comment]
Wow! It looks great after using \mbox. Thank you, Lesley! :)
