### ISSUE TITLE
MG:  Specification parameters module

### ISSUE THREAD

**Issue by LesleyWheat** [Maryamvalian/project741#28]
> Secrets: The values of the specification parameters and constants according to SRS.
> Services: Reads specifications.

In your MIS the Specification parameters module seems to export the parameters, thus their values are not secret to the rest of the program. Maybe secret is "knows storage format of specifications" or something like that. You should likely change the service to "provides specifications".

**Comment by Maryamvalian** [comment]
updated. Thanks
