### ISSUE TITLE
MIS: Issues, MIS of Input Module

### ISSUE THREAD

**Issue by LesleyWheat** [Maryamvalian/project741#35]
>– Check constraints as follows:
>• output: None

How is output a constraint? Say table ## or say it is documented in SRS.

> • transition: Modifies the state variables from the input file:
>– Read sequentially from file and loads state variables from R1 and R2.
>– verify-input()

I think you need to write out descriptions instead of using function names.

**Comment by Maryamvalian** [comment]
Fixed. Thank you!
