### ISSUE TITLE
MIS: main()

### ISSUE THREAD

**Issue by LesleyWheat** [Maryamvalian/project741#36]
Some variables are not defined in SRS or MIS like P_x or P_y.

![image](https://user-images.githubusercontent.com/29044132/226683095-a3e3d186-8cce-409c-99fc-b00325715298.png)

That doesn't seem like proper notation for an or statement nor am I sure what the "or" is for.

**Comment by Maryamvalian** [comment]
Equations can be created either from X-axis or Y-axis. So for creating all possible equations we need both formulas. Each element a_{ij} can be calculated from the first equation or the second equation. Thank you!
