### ISSUE TITLE
MG - Behaviour-Hiding Module - is it supposed to be a group of modules?

### ISSUE THREAD

**Issue by balacij** [Maryamvalian/project741#41]
Does the 7.2 need to have its own Secrets, Services, etc., or can it be understood as just the package of sub-modules? I ask this because I don't think it's a 'leaf' mentioned in the introductory paragraph of chapter 7. If so, then it might be good to make the section title plural and replace the S/S/IB with a small blurb. I'm not quite sure however.

**Comment by balacij** [comment]
Also, same ticket applies to 7.3.

**Comment by Maryamvalian** [comment]
I think it is a grouping, so the modules with the same nature of secrets are collected in the same group such as the 7.2 Behaviour-hiding modules. Thank you for your comment, fixed the title of the section.
