### ISSUE TITLE
MG - Can the Input and Input Verification modules be merged? Same with Output Verif./Format

### ISSUE THREAD

**Issue by balacij** [Maryamvalian/project741#49]
They are heavily tied together because they deal with the structures of the inputs and outputs, so it might be okay to keep them in close proximity too.

**Comment by Maryamvalian** [comment]
It's a very challenging question, Jason! They are heavily tied together as you mentioned. On the other hand, the type of exception is completely different. Also, verification is extremely prone to change!  For example, if someone needs to free some constraints, this module (verification) should be changed. But the input module remains unchanged. So I prefer not to merge them.
