### ISSUE TITLE
update SRS

### ISSUE THREAD

**Issue by Maryamvalian** [Maryamvalian/project741#9]
@smiths Please check my [SRS](https://github.com/Maryamvalian/project741/blob/b26569216e6ce5c16dab78ce92a1a810d1e45428/docs/SRS/SRS.pdf). Thank you for extending the submission deadline for me.

**Comment by smiths** [comment]
Thank you @Maryamvalian.

**Comment by smiths** [comment]
A marked-up copy of the SRS is available in 98f93a3.

I mentioned in the review that the mathematics in the SRS could be improved.  You might want to look at a [summary of a simple mathematical notation](https://gitlab.cas.mcmaster.ca/smiths/se2aa4_cs2me3/-/blob/master/MISFormat/MISFormat.pdf).
